/**
 * Gauntlet semantic model: governed metrics, dimensions and relationships
 * over the pathological warehouse. Deliberately incomplete and sharp-edged.
 *
 * There is no generic `country` dimension. Customer, billing and shipping
 * country are named explicitly. Asking for `country` must refuse.
 */

import { graneConfigSchema, type GraneConfig } from "../../src/config/schema.js";
import { BLOCKED_COLUMNS } from "./data.js";
import { GAUNTLET_TZ } from "./types.js";

export function gauntletConfig(overrides: Record<string, unknown> = {}): GraneConfig {
  return graneConfigSchema.parse({
    project: {
      name: "grane-gauntlet",
      timezone: GAUNTLET_TZ,
      week: { starts: "monday" },
      fiscal_year: { starts_month: "april" },
    },
    connection: { type: "duckdb", path: ":memory:", schema: "main" },
    limits: { max_rows: 10000, default_rows: 1000, timeout_ms: 10000 },
    exploration: {
      enabled: true,
      schemas: ["main"],
      exclude: [...BLOCKED_COLUMNS],
    },
    audit: { enabled: false },
    auth: {
      agents: [
        {
          id: "analyst",
          token: "analyst-token",
          metrics: ["revenue", "orders", "average_order_value"],
          dimensions: ["customer_country", "channel"],
          exploration: true,
        },
        {
          id: "intern",
          token: "intern-token",
          metrics: ["revenue"],
          dimensions: ["channel"],
          exploration: false,
        },
      ],
    },
    entities: {
      customer: { table: "customers", primary_key: "id", description: "A registered person." },
      order: { table: "orders", primary_key: "id", description: "An order. Most money metrics live here." },
      product: { table: "products", primary_key: "id" },
      account: { table: "accounts", primary_key: "id" },
      ticket: { table: "support_tickets", primary_key: "id" },
      snapshot: { table: "daily_account_snapshots", primary_key: "id" },
      employee: { table: "employees", primary_key: "id" },
      chain_f: { table: "chain_f", primary_key: "id" },
    },
    metrics: {
      revenue: {
        description: "Net amount of completed orders, measured at completed_at.",
        owner: "finance",
        entity: "order",
        type: "sum",
        sql: "${orders.net_amount}",
        time_dimension: "${orders.completed_at}",
        unit: "GBP",
        status: "approved",
        synonyms: ["sales", "net sales"],
        filters: { "orders.status": "completed" },
      },
      orders: {
        description: "Count of completed orders.",
        entity: "order",
        type: "count",
        sql: "${orders.id}",
        time_dimension: "${orders.completed_at}",
        filters: { "orders.status": "completed" },
      },
      ordering_customers: {
        description: "Distinct customers on completed orders (order grain).",
        entity: "order",
        type: "count_distinct",
        sql: "${orders.customer_id}",
        time_dimension: "${orders.completed_at}",
        filters: { "orders.status": "completed" },
      },
      average_order_value: {
        description: "Revenue / completed orders. Divide-by-zero safe.",
        entity: "order",
        type: "ratio",
        numerator: "revenue",
        denominator: "orders",
        synonyms: ["aov"],
      },
      revenue_per_customer: {
        description: "Revenue / distinct ordering customers.",
        entity: "order",
        type: "ratio",
        numerator: "revenue",
        denominator: "ordering_customers",
      },
      successful_revenue: {
        description: "Succeeded payment amounts, pre-aggregated at order grain.",
        entity: "order",
        type: "sum",
        sql: "${payments.amount}",
        time_dimension: "${orders.completed_at}",
        filters: { "payments.status": "succeeded" },
      },
      refunded_amount: {
        entity: "order",
        type: "sum",
        sql: "${refunds.amount}",
        time_dimension: "${orders.completed_at}",
      },
      conversion_rate: {
        description: "Completed orders / all orders (same grain).",
        entity: "order",
        type: "ratio",
        numerator: "orders",
        denominator: "all_orders",
      },
      all_orders: {
        entity: "order",
        type: "count",
        sql: "${orders.id}",
        time_dimension: "${orders.created_at}",
      },
      avg_order_amount: {
        description: "AVG of order net_amount. Must not become an average of averages.",
        entity: "order",
        type: "avg",
        sql: "${orders.net_amount}",
        time_dimension: "${orders.completed_at}",
        filters: { "orders.status": "completed" },
      },
      customers: {
        description: "Headcount of the customers table, not distinct buyers.",
        entity: "customer",
        type: "count",
        sql: "${customers.id}",
        time_dimension: "${customers.created_at}",
      },
      account_balance: {
        description:
          "Semi-additive: may be summed across accounts at one snapshot date, never across dates.",
        entity: "snapshot",
        type: "sum",
        sql: "${daily_account_snapshots.balance}",
        time_dimension: "${daily_account_snapshots.snapshot_date}",
        additive: "semi",
        semi_additive: { window: "last", group_by: ["${daily_account_snapshots.account_id}"] },
      },
      inventory: {
        description: "Non-additive inventory level at product grain.",
        entity: "product",
        type: "sum",
        sql: "${products.inventory_level}",
      },
      chain_value: {
        description: "Value at the far end of a six-table chain.",
        entity: "chain_f",
        type: "sum",
        sql: "${chain_f.value}",
      },
    },
    dimensions: {
      customer_country: { entity: "customer", sql: "${customers.country}", type: "string" },
      customer_type: { entity: "customer", sql: "${customers.customer_type}", type: "string" },
      channel: { entity: "order", sql: "${orders.channel}", type: "string" },
      order_status: { entity: "order", sql: "${orders.status}", type: "string" },
      billing_country: { entity: "order", sql: "${billing_addresses.country}", type: "string" },
      shipping_country: { entity: "order", sql: "${shipping_addresses.country}", type: "string" },
      product_category: { entity: "product", sql: "${products.category}", type: "string" },
      product_name: { entity: "product", sql: "${products.name}", type: "string" },
      ticket_category: { entity: "ticket", sql: "${support_tickets.category}", type: "string" },
      session_browser: { entity: "customer", sql: "${sessions.browser}", type: "string" },
      experiment_variant: { entity: "customer", sql: "${experiment_assignments.variant}", type: "string" },
      account_name: { entity: "account", sql: "${accounts.name}", type: "string" },
      campaign_name: { entity: "order", sql: "${campaigns.name}", type: "string" },
      checkout_error: { entity: "order", sql: "${checkout_events.error}", type: "string" },
      plan_name: { entity: "customer", sql: "${plans.name}", type: "string" },
      chain_a_label: { entity: "chain_f", sql: "${chain_a.label}", type: "string" },
      completed_at: { entity: "order", sql: "${orders.completed_at}", type: "timestamp" },
      created_at: { entity: "order", sql: "${orders.created_at}", type: "timestamp" },
    },
    relationships: {
      orders_to_customers: { from: "orders.customer_id", to: "customers.id", type: "many_to_one" },
      customers_to_countries: { from: "customers.country_id", to: "countries.id", type: "many_to_one" },
      billing_to_orders: { from: "billing_addresses.order_id", to: "orders.id", type: "one_to_one" },
      shipping_to_orders: { from: "shipping_addresses.order_id", to: "orders.id", type: "one_to_one" },
      billing_to_countries: { from: "billing_addresses.country_id", to: "countries.id", type: "many_to_one" },
      shipping_to_countries: { from: "shipping_addresses.country_id", to: "countries.id", type: "many_to_one" },
      payments_to_orders: { from: "payments.order_id", to: "orders.id", type: "many_to_one" },
      refunds_to_orders: { from: "refunds.order_id", to: "orders.id", type: "many_to_one" },
      order_items_to_orders: { from: "order_items.order_id", to: "orders.id", type: "many_to_one" },
      order_items_to_products: { from: "order_items.product_id", to: "products.id", type: "many_to_one" },
      product_map_to_products: {
        from: "product_category_map.product_id",
        to: "products.id",
        type: "many_to_one",
      },
      product_map_to_categories: {
        from: "product_category_map.category_id",
        to: "product_categories.id",
        type: "many_to_one",
      },
      tickets_to_customers: { from: "support_tickets.customer_id", to: "customers.id", type: "many_to_one" },
      sessions_to_customers: { from: "sessions.customer_id", to: "customers.id", type: "many_to_one" },
      checkout_to_sessions: { from: "checkout_events.session_id", to: "sessions.id", type: "many_to_one" },
      checkout_to_orders: { from: "checkout_events.order_id", to: "orders.id", type: "many_to_one" },
      assignments_to_customers: {
        from: "experiment_assignments.customer_id",
        to: "customers.id",
        type: "many_to_one",
      },
      members_to_accounts: { from: "account_members.account_id", to: "accounts.id", type: "many_to_one" },
      members_to_customers: { from: "account_members.customer_id", to: "customers.id", type: "many_to_one" },
      attribution_to_orders: { from: "attribution_events.order_id", to: "orders.id", type: "many_to_one" },
      attribution_to_campaigns: {
        from: "attribution_events.campaign_id",
        to: "campaigns.id",
        type: "many_to_one",
      },
      subscriptions_to_customers: {
        from: "subscriptions.customer_id",
        to: "customers.id",
        type: "many_to_one",
      },
      subscriptions_to_plans: { from: "subscriptions.plan_id", to: "plans.id", type: "many_to_one" },
      invoices_to_accounts: { from: "invoices.account_id", to: "accounts.id", type: "many_to_one" },
      invoice_lines_to_invoices: { from: "invoice_lines.invoice_id", to: "invoices.id", type: "many_to_one" },
      snapshots_to_accounts: {
        from: "daily_account_snapshots.account_id",
        to: "accounts.id",
        type: "many_to_one",
      },
      chain_b_to_a: { from: "chain_b.a_id", to: "chain_a.id", type: "many_to_one" },
      chain_c_to_b: { from: "chain_c.b_id", to: "chain_b.id", type: "many_to_one" },
      chain_d_to_c: { from: "chain_d.c_id", to: "chain_c.id", type: "many_to_one" },
      chain_e_to_d: { from: "chain_e.d_id", to: "chain_d.id", type: "many_to_one" },
      chain_f_to_e: { from: "chain_f.e_id", to: "chain_e.id", type: "many_to_one" },
      cycle_a_to_b: { from: "cycle_a.b_id", to: "cycle_b.id", type: "many_to_one" },
      cycle_b_to_c: { from: "cycle_b.c_id", to: "cycle_c.id", type: "many_to_one" },
      cycle_c_to_a: { from: "cycle_c.a_id", to: "cycle_a.id", type: "many_to_one" },
    },
    ...overrides,
  });
}
